#!/bin/bash
#Author:黄兴立
#Function:git clone

function gitForGit()
{
    if [ $# -lt 2 ]
    then
        echo "You don't have enough parameters"
    else
        git clone git@github.com:${1}/${2}
    fi
}

function gitForHttps()
{
    if [ $# -lt 2 ]
    then
        echo "You don't have enough parameters"
    else
        git clone https://github.com/${1}/${2}
    fi
}

if [ $# -lt 2 ]
then
    echo "You don't have enough parameters"
elif [ $# -eq 2 ]
then
    if [ ${1:0:1} == '-' ]
    then
        echo "You don't have correct parameters"
    else
        gitForGit $1 $2
    fi
else
    if [ ${1:0:1} == '-' ]
    then
        if [ ${#1} -eq 2 ]
        then
            case ${1:1:1} in
                'g') gitForGit $2 $3
                ;;
                'h') gitForHttps $2 $3
                ;;
                *) echo "You don't have correct parameters"
                ;;
            esac
        else
            echo "You don't have correct parameters"
        fi
    else
        gitForGit $1 $2
    fi
fi